#!/usr/bin/env bash
# scripts/okx/start_with_creds.sh
#
# Start okx-trade-mcp (or any OKX CLI) with API credentials sourced
# from macOS Keychain — never written to the repo and never logged.
#
# Loop-engineered: idempotent, self-verifying, leaves no secrets behind.
#
# ADR-0011 D7: OKX three secrets live in Keychain only.
#   - service: "cryptoagg-okx" (real) or "cryptoagg-okx-mock" (--mock)
#   - accounts: api-key, secret-key, passphrase
#
# OKX_PAPER_MODE is intentionally NOT in Keychain (deployment
# decision, env variable, ADR-0011 D7).
#
# Usage:
#   scripts/okx/start_with_creds.sh --check
#   scripts/okx/start_with_creds.sh --rotate
#   scripts/okx/start_with_creds.sh --mock          # Phase 1A walkthrough: use cryptoagg-okx-mock service
#   scripts/okx/start_with_creds.sh [--mock] okx-trade-mcp --modules market --read-only
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
LOCAL_BIN="${ROOT}/scripts/okx/.bin"
CONFIG_DIR="${ROOT}/.scratch/okx_state"
CONFIG_FILE="${CONFIG_DIR}/config.toml"
TMP_DIR="$(mktemp -d -t okx-creds.XXXXXX)"
chmod 700 "$TMP_DIR"
trap 'rm -rf "$TMP_DIR"' EXIT

# ── helpers (defined first so they're available in main) ──────────────────

read_secret() {
    local account="$1"
    local value
    if ! value="$(security find-generic-password \
            -s "$KEYCHAIN_SERVICE" -a "$account" -w 2>/dev/null)"; then
        echo "ERROR: Keychain entry missing: service=$KEYCHAIN_SERVICE account=$account" >&2
        echo "  Add it with:" >&2
        echo "    security add-generic-password -s $KEYCHAIN_SERVICE -a $account -w" >&2
        echo "  Or re-run with --mock to use cryptoagg-okx-mock service." >&2
        return 1
    fi
    printf '%s' "$value"
}

emit_config_toml() {
    local api_key="$1"
    local secret_key="$2"
    local passphrase="$3"
    cat <<TOML
# Generated by scripts/okx/start_with_creds.sh - never edit by hand.
# Source: macOS Keychain service="$KEYCHAIN_SERVICE" (mode=$MODE).
# This file is chmod 600 and is NOT git-tracked (see .gitignore).

[profile.default]
api_key = "${api_key}"
secret_key = "${secret_key}"
passphrase = "${passphrase}"
demo = true
TOML
}

check_all_entries() {
    echo "==> Checking Keychain entries (existence only, no values read)..."
    local missing=0
    for account in api-key secret-key passphrase; do
        if security find-generic-password \
                -s "$KEYCHAIN_SERVICE" -a "$account" >/dev/null 2>&1; then
            echo "    [OK] $account"
        else
            echo "    [MISSING] $account"
            missing=1
        fi
    done
    if [[ $missing -eq 1 ]]; then
        echo "==> Missing entries. Add with:" >&2
        echo "    security add-generic-password -s $KEYCHAIN_SERVICE -a <account> -w" >&2
        exit 2
    fi
    echo "==> All required entries present (service=$KEYCHAIN_SERVICE)."
    exit 0
}

# ── flag parsing ───────────────────────────────────────────────────────────

# Default state — MODE/KEYCHAIN_SERVICE may be overridden by --mock below.
KEYCHAIN_SERVICE="cryptoagg-okx"
MODE="real"

# --help: print and exit first.
for arg in "$@"; do
    case "$arg" in
        --help|-h)
            sed -n '2,28p' "$0"
            exit 0
            ;;
    esac
done

# Build a clean argv with the recognized flags stripped, preserving order.
CLEAN=()
for arg in "$@"; do
    case "$arg" in
        --check) CLEAN+=("$arg") ;;  # keep for later dispatch
        --rotate) CLEAN+=("$arg") ;;
        --mock)
            MODE="mock"
            KEYCHAIN_SERVICE="cryptoagg-okx-mock"
            ;;
        *) CLEAN+=("$arg") ;;
    esac
done
if [[ ${#CLEAN[@]} -gt 0 ]]; then set -- "${CLEAN[@]}"; else set --; fi

# Dispatch: --check exits before main path; --rotate is a no-op flag (main
# path always overwrites config.toml when entries exist, which is the
# same as rotate behavior).
for arg in "$@"; do
    case "$arg" in
        --check) check_all_entries ;;
    esac
done
# Strip --check and --rotate from argv before exec.
EXEC=()
for arg in "$@"; do
    case "$arg" in
        --check|--rotate) ;;
        *) EXEC+=("$arg") ;;
    esac
done
if [[ ${#EXEC[@]} -gt 0 ]]; then set -- "${EXEC[@]}"; else set --; fi

# ── main ───────────────────────────────────────────────────────────────────

mkdir -p "$CONFIG_DIR"

api_key="$(read_secret api-key)"
secret_key="$(read_secret secret-key)"
passphrase="$(read_secret passphrase)"

# Build config in temp file, chmod 600 before any rename.
tmp_config="$TMP_DIR/config.toml"
emit_config_toml "$api_key" "$secret_key" "$passphrase" > "$tmp_config"
chmod 600 "$tmp_config"
mv -f "$tmp_config" "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE"

echo "==> Wrote $CONFIG_FILE (chmod 600, never logged)"

# Scrub in-memory secrets.
unset api_key secret_key passphrase

# Forward any extra argv to the real binary.
if [[ $# -gt 0 ]]; then
    # If mock mode and binary is a shim, prepend LOCAL_BIN to PATH.
    if [[ "$MODE" == "mock" ]] && [[ ":$PATH:" != *":$LOCAL_BIN:"* ]]; then
        export PATH="$LOCAL_BIN:$PATH"
    fi
    echo "==> Launching: $*"
    exec "$@"
fi
echo "==> Done. Config ready at $CONFIG_FILE (service=$KEYCHAIN_SERVICE, mode=$MODE)"
