"""Signal → FreqtradeStrategy translator.

Converts a HarmonicSignal (cryptoagg domain) into a Freqtrade IStrategy Python file.

Translation modes (ADR-0010):
  Pattern-driven  — signal has concrete entry/exit/ZPRC → direct signal mapping
  Indicator-driven — signal + ATR_RATIO/RSI threshold → indicator-based strategy
  Regime-driven    — signal carries regime tag → multiple timeframe/strategy selection

Output lives in .scratch/loop_state/freqtrade/strategies/{strategy_name}.py
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

STRATEGY_DIR = Path(".scratch/loop_state/freqtrade/strategies")
STRATEGY_DIR.mkdir(parents=True, exist_ok=True)

Mode = Literal["pattern", "indicator", "regime"]


@dataclass
class HarmonicSignal:
    """Minimal signal representation consumed by the translator."""

    pattern_type: str  # e.g. "Gartley", "Bat", "Butterfly"
    entry_price: float | None
    exit_price: float | None
    stop_loss: float | None
    zrpc_price: float | None  # Potential Reversal Zone price
    confidence: float  # 0.0–1.0
    regime: str | None  # e.g. "bullish", "bearish", "ranging"


@dataclass
class TranslatorConfig:
    """Configuration for the translation."""

    timeframe: str = "1h"
    stake_amount: float = 100.0
    dry_run: bool = True
    can_short: bool = False
    trailing_stop: bool = False
    stoploss: float = -0.10


def translate(signal: HarmonicSignal, config: TranslatorConfig, mode: Mode = "pattern") -> Path:
    """Translate a HarmonicSignal into a Freqtrade IStrategy file.

    Args:
        signal: The harmonic pattern signal to translate.
        config: Freqtrade strategy configuration.
        mode: Translation mode (pattern | indicator | regime).

    Returns:
        Path to the generated strategy file.

    Raises:
        ValueError: If mode is unknown or required signal fields are missing for the mode.
    """
    if mode == "pattern":
        return _translate_pattern(signal, config)
    elif mode == "indicator":
        return _translate_indicator(signal, config)
    elif mode == "regime":
        return _translate_regime(signal, config)
    else:
        raise ValueError(f"Unknown translation mode: {mode}")


def _translate_pattern(signal: HarmonicSignal, config: TranslatorConfig) -> Path:
    """Pattern-driven translation: direct entry/exit/sl from signal fields."""
    if signal.entry_price is None or signal.exit_price is None or signal.stop_loss is None:
        raise ValueError(
            f"pattern mode requires entry_price, exit_price, stop_loss; "
            f"got entry={signal.entry_price} exit={signal.exit_price} sl={signal.stop_loss}"
        )

    strategy_name = f"Harmonic{signal.pattern_type.replace(' ', '')}{config.timeframe.replace('/', '')}"

    source = textwrap.dedent(f'''\
        # HarmonicSignal → FreqtradeStrategy (pattern-driven)
        # Source signal: {signal.pattern_type} confidence={signal.confidence:.2f}
        # Generated by app.services.freqtrade.translator (do not edit manually)

        from freqtrade.strategy import IStrategy
        from freqtrade.resolver import StrategyResolver
        from pandas import DataFrame


        class {strategy_name}(IStrategy):
            timeframe = "{config.timeframe}"
            stoploss = {config.stoploss}
            trailing_stop = {config.trailing_stop}
            can_short = {config.can_short}
            dry_run = {config.dry_run}

            # Minimal ROI (placeholder — hyperopt will tune)
            minimal_roi = {{
                "0": 0.05,
                "30": 0.03,
                "60": 0.01,
            }}

            # Harmonic pattern entry signals
            # Entry:  {signal.entry_price}
            # Exit:   {signal.exit_price}
            # Stop:   {signal.stop_loss}
            # ZRPC:   {signal.zrpc_price}
            # Confidence: {signal.confidence:.2f}

            def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                # Placeholder: integrate with cryptoagg signal engine
                # dataframe['entry_signal'] = ...
                # dataframe['exit_signal'] = ...
                return dataframe

            def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                dataframe['buy'] = 0
                return dataframe

            def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                dataframe['sell'] = 0
                return dataframe
        ''')

    return _write_strategy(strategy_name, source)


def _translate_indicator(signal: HarmonicSignal, config: TranslatorConfig) -> Path:
    """Indicator-driven: use ATR_RATIO / RSI thresholds from signal."""
    strategy_name = f"IndDriver{signal.pattern_type.replace(' ', '')}{config.timeframe.replace('/', '')}"

    source = textwrap.dedent(f'''\
        # HarmonicSignal → FreqtradeStrategy (indicator-driven)
        # Source signal: {signal.pattern_type} confidence={signal.confidence:.2f}
        # Generated by app.services.freqtrade.translator (do not edit manually)

        from freqtrade.strategy import IStrategy
        from pandas import DataFrame


        class {strategy_name}(IStrategy):
            timeframe = "{config.timeframe}"
            stoploss = {config.stoploss}
            trailing_stop = {config.trailing_stop}
            can_short = {config.can_short}
            dry_run = {config.dry_run}

            minimal_roi = {{
                "0": 0.05,
                "30": 0.03,
                "60": 0.01,
            }}

            def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                # Integrate with cryptoagg signal engine:
                # - ATR-based entry confirmation
                # - RSI threshold gates
                # - Pattern confidence weighting
                return dataframe

            def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                dataframe['buy'] = 0
                return dataframe

            def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                dataframe['sell'] = 0
                return dataframe
        ''')

    return _write_strategy(strategy_name, source)


def _translate_regime(signal: HarmonicSignal, config: TranslatorConfig) -> Path:
    """Regime-driven: regime tag determines strategy selection."""
    strategy_name = f"RegimeDriver{signal.pattern_type.replace(' ', '')}{config.timeframe.replace('/', '')}"

    source = textwrap.dedent(f'''\
        # HarmonicSignal → FreqtradeStrategy (regime-driven)
        # Source signal: {signal.pattern_type} regime={signal.regime} confidence={signal.confidence:.2f}
        # Generated by app.services.freqtrade.translator (do not edit manually)

        from freqtrade.strategy import IStrategy
        from pandas import DataFrame


        class {strategy_name}(IStrategy):
            timeframe = "{config.timeframe}"
            stoploss = {config.stoploss}
            trailing_stop = {config.trailing_stop}
            can_short = {config.can_short}
            dry_run = {config.dry_run}

            minimal_roi = {{
                "0": 0.05,
                "30": 0.03,
                "60": 0.01,
            }}

            def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                # Regime: {signal.regime}
                # Select indicators based on regime:
                #   bullish  → trend-following (EMA cross, MACD)
                #   bearish  → mean-reversion (RSI, Bollinger)
                #   ranging  → breakout (ATR volatility)
                return dataframe

            def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                dataframe['buy'] = 0
                return dataframe

            def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                dataframe['sell'] = 0
                return dataframe
        ''')

    return _write_strategy(strategy_name, source)


def _write_strategy(name: str, source: str) -> Path:
    """Write strategy source to file and return the path."""
    path = STRATEGY_DIR / f"{name}.py"
    path.write_text(source)
    return path
