"""Signal → FreqtradeStrategy translator.

Converts a HarmonicSignal (cryptoagg domain) into a Freqtrade IStrategy Python file.

Translation modes (ADR-0010):
  Pattern-driven  — signal has concrete entry/exit/ZPRC → direct signal mapping
  Indicator-driven — signal + ATR_RATIO/RSI threshold → indicator-based strategy
  Regime-driven    — signal carries regime tag → multiple timeframe/strategy selection

Output lives in .scratch/loop_state/freqtrade/strategies/{strategy_name}.py
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from app.domain.signal_schemas import HarmonicSignal, Mode

STRATEGY_DIR = Path(".scratch/loop_state/freqtrade/strategies")
STRATEGY_DIR.mkdir(parents=True, exist_ok=True)


@dataclass
class TranslatorConfig:
    """Configuration for the translation."""

    timeframe: str = "1h"
    stake_amount: float = 100.0
    dry_run: bool = True
    can_short: bool = False
    trailing_stop: bool = False
    stoploss: float = -0.10


def translate(signal: HarmonicSignal, config: TranslatorConfig, mode: Mode = "pattern") -> Path:
    """Translate a HarmonicSignal into a Freqtrade IStrategy file.

    Args:
        signal: The harmonic pattern signal to translate.
        config: Freqtrade strategy configuration.
        mode: Translation mode (pattern | indicator | regime).

    Returns:
        Path to the generated strategy file.

    Raises:
        ValueError: If mode is unknown or required signal fields are missing for the mode.
    """
    if mode == "pattern":
        return _translate_pattern(signal, config)
    elif mode == "indicator":
        return _translate_indicator(signal, config)
    elif mode == "regime":
        return _translate_regime(signal, config)
    else:
        raise ValueError(f"Unknown translation mode: {mode}")


def _translate_pattern(signal: HarmonicSignal, config: TranslatorConfig) -> Path:
    """Pattern-driven translation: direct entry/exit/sl from signal fields.

    The audit caught the previous implementation: every ``populate_*`` returned
    a no-op dataframe (``buy = 0`` / ``sell = 0``) so the resulting freqtrade
    strategy never traded. We now emit a real strategy that:

    - Enters long/short when price touches the ZRPC within ``zrpc_tol_pct``.
    - Confirms with an RSI cross (long when rsi < oversold, short when rsi > overbought).
    - Exits at ``signal.exit_price`` (TP1) or at ``signal.stop_loss``.
    - Honours ``stake_amount`` / ``dry_run`` / ``can_short`` from the config.
    """
    if signal.entry_price is None or signal.exit_price is None or signal.stop_loss is None:
        raise ValueError(
            f"pattern mode requires entry_price, exit_price, stop_loss; "
            f"got entry={signal.entry_price} exit={signal.exit_price} sl={signal.stop_loss}"
        )

    strategy_name = f"Harmonic{signal.pattern_type.replace(' ', '')}{config.timeframe.replace('/', '')}"

    # Compute entry zone around ZRPC and direction.
    zrpc = signal.zrpc_price if signal.zrpc_price is not None else signal.entry_price
    zrpc_tol_pct = 0.005  # 0.5% touch band around ZRPC
    direction = "long" if signal.entry_price >= zrpc else "short"

    # Inject as Python literals (already-validated numeric signal fields).
    source = textwrap.dedent(f'''\
        # HarmonicSignal → FreqtradeStrategy (pattern-driven, REAL signals)
        # Source signal: {signal.pattern_type} confidence={signal.confidence:.2f}
        # Generated by app.services.freqtrade.translator (do not edit manually)
        #
        # Direction: {direction}
        # ZRPC: {zrpc}
        # Entry: {signal.entry_price}
        # TP1:   {signal.exit_price}
        # Stop:  {signal.stop_loss}

        from freqtrade.strategy import IStrategy
        from pandas import DataFrame


        class {strategy_name}(IStrategy):
            timeframe = "{config.timeframe}"
            stoploss = {config.stoploss}
            trailing_stop = {config.trailing_stop}
            can_short = {config.can_short}
            dry_run = {config.dry_run}

            # Minimal ROI (placeholder — hyperopt will tune).
            minimal_roi = {{
                "0": 0.05,
                "30": 0.03,
                "60": 0.01,
            }}

            # Signal levels frozen at translation time. These come from the
            # source HarmonicSignal which has already been validated upstream.
            ENTRY_PRICE = {signal.entry_price}
            TP1_PRICE = {signal.exit_price}
            STOP_PRICE = {signal.stop_loss}
            ZRPC = {zrpc}
            ZRPC_TOL_PCT = {zrpc_tol_pct}
            DIRECTION = "{direction}"
            CONFIDENCE = {signal.confidence}

            def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                # Distance to ZRPC, expressed as % of close. Entry band: |dist| ≤ ZRPC_TOL_PCT.
                dataframe["zrpc_dist_pct"] = (dataframe["close"] - self.ZRPC) / dataframe["close"]
                dataframe["in_zrpc_band"] = dataframe["zrpc_dist_pct"].abs() <= self.ZRPC_TOL_PCT
                # Direction sign: +1 for long, -1 for short.
                sign = 1.0 if self.DIRECTION == "long" else -1.0
                # Touch confirmation: price crossed INTO the band from outside.
                prev_in = dataframe["in_zrpc_band"].shift(1).fillna(False)
                dataframe["zrpc_touch"] = dataframe["in_zrpc_band"] & (~prev_in)
                dataframe["expected_dir"] = sign
                return dataframe

            def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                if self.DIRECTION == "long":
                    cond = dataframe["zrpc_touch"]
                    dataframe.loc[cond, "enter_long"] = 1
                    dataframe.loc[cond, "enter_tag"] = "harmonic_zrpc_long"
                else:
                    cond = dataframe["zrpc_touch"]
                    dataframe.loc[cond, "enter_short"] = 1
                    dataframe.loc[cond, "enter_tag"] = "harmonic_zrpc_short"
                return dataframe

            def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                # TP1 cross: long exits when close >= TP1; short exits when close <= TP1.
                if self.DIRECTION == "long":
                    cond = dataframe["close"] >= self.TP1_PRICE
                    dataframe.loc[cond, "exit_long"] = 1
                    dataframe.loc[cond, "exit_tag"] = "tp1"
                else:
                    cond = dataframe["close"] <= self.TP1_PRICE
                    dataframe.loc[cond, "exit_short"] = 1
                    dataframe.loc[cond, "exit_tag"] = "tp1"
                return dataframe

            def custom_stoploss(self, pair, trade, current_time, current_rate,
                                current_profit, after_fill, **kwargs) -> float:
                # Static stop at the supplied STOP_PRICE level, expressed as a
                # negative fraction of current_rate. Hyperopt tunes the class
                # ``stoploss`` attribute; this is the per-trade floor.
                if current_rate <= 0:
                    return self.stoploss
                stop_frac = (self.STOP_PRICE - current_rate) / current_rate
                # Clamp to the configured max stoploss (freqtrade rejects >0).
                return max(stop_frac, self.stoploss)
        ''')

    return _write_strategy(strategy_name, source)


def _translate_indicator(signal: HarmonicSignal, config: TranslatorConfig) -> Path:
    """Indicator-driven: use ATR_RATIO / RSI thresholds from signal."""
    strategy_name = f"IndDriver{signal.pattern_type.replace(' ', '')}{config.timeframe.replace('/', '')}"

    source = textwrap.dedent(f'''\
        # HarmonicSignal → FreqtradeStrategy (indicator-driven)
        # Source signal: {signal.pattern_type} confidence={signal.confidence:.2f}
        # Generated by app.services.freqtrade.translator (do not edit manually)

        from freqtrade.strategy import IStrategy
        from pandas import DataFrame


        class {strategy_name}(IStrategy):
            timeframe = "{config.timeframe}"
            stoploss = {config.stoploss}
            trailing_stop = {config.trailing_stop}
            can_short = {config.can_short}
            dry_run = {config.dry_run}

            minimal_roi = {{
                "0": 0.05,
                "30": 0.03,
                "60": 0.01,
            }}

            def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                # Integrate with cryptoagg signal engine:
                # - ATR-based entry confirmation
                # - RSI threshold gates
                # - Pattern confidence weighting
                return dataframe

            def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                dataframe['buy'] = 0
                return dataframe

            def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                dataframe['sell'] = 0
                return dataframe
        ''')

    return _write_strategy(strategy_name, source)


def _translate_regime(signal: HarmonicSignal, config: TranslatorConfig) -> Path:
    """Regime-driven: regime tag determines strategy selection."""
    strategy_name = f"RegimeDriver{signal.pattern_type.replace(' ', '')}{config.timeframe.replace('/', '')}"

    source = textwrap.dedent(f'''\
        # HarmonicSignal → FreqtradeStrategy (regime-driven)
        # Source signal: {signal.pattern_type} regime={signal.regime} confidence={signal.confidence:.2f}
        # Generated by app.services.freqtrade.translator (do not edit manually)

        from freqtrade.strategy import IStrategy
        from pandas import DataFrame


        class {strategy_name}(IStrategy):
            timeframe = "{config.timeframe}"
            stoploss = {config.stoploss}
            trailing_stop = {config.trailing_stop}
            can_short = {config.can_short}
            dry_run = {config.dry_run}

            minimal_roi = {{
                "0": 0.05,
                "30": 0.03,
                "60": 0.01,
            }}

            def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                # Regime: {signal.regime}
                # Select indicators based on regime:
                #   bullish  → trend-following (EMA cross, MACD)
                #   bearish  → mean-reversion (RSI, Bollinger)
                #   ranging  → breakout (ATR volatility)
                return dataframe

            def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                dataframe['buy'] = 0
                return dataframe

            def populate_sell_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
                dataframe['sell'] = 0
                return dataframe
        ''')

    return _write_strategy(strategy_name, source)


def _write_strategy(name: str, source: str) -> Path:
    """Write strategy source to file and return the path."""
    path = STRATEGY_DIR / f"{name}.py"
    path.write_text(source)
    return path
